### ISSUE TITLE
Error when make html

### ISSUE THREAD

**Issue by michelcmorel** [marijnh/Eloquent-JavaScript#158]
Hi there,
I am using ubuntu 14.04 and when I run from terminal "sudo make html", I get the following build error:

PATH=node_modules/codemirror/bin:/home/michel/.rbenv/plugins/ruby-build/bin:/home/michel/.rbenv/shims:/home/michel/.rbenv/bin:/home/michel/.rvm/gems/ruby-2.1.2/bin:/home/michel/.rvm/gems/ruby-2.1.2@global/bin:/home/michel/.rvm/rubies/ruby-2.1.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/michel/.rvm/bin:/home/michel/.rvm/bin asciidoc -f asciidoc_html.conf --backend=html5 -o html/21_skillsharing.html 21_skillsharing.txt
node bin/build_code.js 21_skillsharing.txt
node bin/chapter_info.js > html/js/chapter_info.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'jszip'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at chapterZipFile (/home/michel/Documents/Eloquent-JavaScript/bin/chapter_info.js:208:18)
    at output.push.title (/home/michel/Documents/Eloquent-JavaScript/bin/chapter_info.js:26:13)
    at Array.forEach (native)
    at Object.<anonymous> (/home/michel/Documents/Eloquent-JavaScript/bin/chapter_info.js:13:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
make: *** [html/js/chapter_info.js] Error 8

Can you please advise if you have come across this error before?
Thank you,
Michel

**Comment by hjoaco** [comment]
executed only **make html** without **sudo**.
a ver que dice ruby!

**Comment by michelcmorel** [comment]
True! It worked like a charm. Thank you very much. Michel
