### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by drom** [marijnh/Eloquent-JavaScript#189]
I am running node v4, doing `npm install`, getting following issue:

```sh
drom@drom:~/work/github/drom/Eloquent-JavaScript> npm i
npm WARN package.json Eloquent-JavaScript@0.1.0 license should be a valid SPDX license expression
npm WARN package.json Dependency 'jszip' exists in both dependencies and devDependencies, using 'jszip@^2.5.0' from dependencies
 
> canvas@1.3.5 install /home/drom/work/github/drom/Eloquent-JavaScript/node_modules/canvas
> node-gyp rebuild

gyp: /usr/lib64/node_modules/npm/node_modules/node-gyp/addon-rpm.gypi not found (cwd: /home/drom/work/github/drom/Eloquent-JavaScript/node_modules/canvas) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:358:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-5-default
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/drom/work/github/drom/Eloquent-JavaScript/node_modules/canvas
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
 
> contextify@0.1.13 install /home/drom/work/github/drom/Eloquent-JavaScript/node_modules/contextify
> node-gyp rebuild

gyp: /usr/lib64/node_modules/npm/node_modules/node-gyp/addon-rpm.gypi not found (cwd: /home/drom/work/github/drom/Eloquent-JavaScript/node_modules/contextify) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/configure.js:358:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-5-default
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/drom/work/github/drom/Eloquent-JavaScript/node_modules/contextify
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.13-5-default
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/drom/work/github/drom/Eloquent-JavaScript/npm-debug.log
```

**Comment by marijnh** [comment]
Yes, unfortunately, the canvas package is and remains a pain to build. I've had it break several times before, and I guess this one might be due to using an NPM version that's not a 0.x. If someone wants to look into this, that'd be great, but I don't really care enough (canvas is just an obscure dependency used to run part of the test suite outside of the browser).

**Comment by angus-c** [comment]
@drom If you only need to load the html (inc. sandbox) you can drop the canvas dependency

**Comment by drom** [comment]
@angus-c thank you. Are you running into the same issue?

**Comment by marijnh** [comment]
Attached patch resolves this

**Comment by drom** [comment]
Thank you for fixing it!
