### ISSUE TITLE
make book.epub fails due to TypeError in TOC

### ISSUE THREAD

**Issue by andypillip** [marijnh/Eloquent-JavaScript#467]
Thanks very much for the free book!

I saw that you can generate different PDFs, which is great, but PDF still stinks. When trying to generate the epub, I get the following error, though:

```
TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/home/andy/EDV/Eloquent-JavaScript/src/generate_epub_toc.js:16:46)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
make: *** [Makefile:71: epub/toc.xhtml] Fehler 1
```

**Comment by andypillip** [comment]
Actually I ran it a second time and suddenly it worked…
